[project]
name = "reddit-summarizer-mcp"
version = "0.1.0"
description = "Reddit summarizer mcp server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpraw>=7.8.1",
    "httpx>=0.28.1",
    "mcp[cli]>=1.11.0",
    "python-dotenv>=1.1.1",
]
